---
title: "Prequel to Hawkes Processes: An Overview of Temporal and Spatio-Temporal Point Processes and Some Simulations"
author: "Frances Lin"
date: "June 2021"
output: pdf_document
---

Major Professor: James Molyneux

Committee Members: Lisa Madsen & Charlotte Wickham

# Abstract

# 1 Introduction 

Hawkes process is also known as a self-exciting point process. 

## Motivation 

## Applications

Applications of Hawkes processes can be found in a wide variety of fields such as seismology, criminology, insurance, finance, social network, and neuroscience.

The defining characteristic of Hawkes processes is that it is self-exciting. In other words, the occurrence of an event increases the occurrence of future events. For example, in seismology, an event can be an earthquake occurrence that causes aftershocks. In criminology, an event can be a gang rivalry that triggers retaliations following the gang crime. In insurance, an event can be a standard claim that increases claims. In finance, an event can be a transcation that influences future prices or volumes of transcations or a news that leads to movements in stock prices or trading behaviors. In social network, an event can be a tweet about an event on Twitter that follows a cascade of retweets from other users on the same social networking platform. In neuroscience, an event can be firing of a neuron that triggers spikes (or action potentials) of other neurons.

## Objectives

The objectives of this project is to give an overview of various types of point processes so that readers of interest have the necessary background knowledge to understand Hawkes process. The overview includes

1. defining and discussing properties of counting process, (homogeneous) Poisson process, nonhomogeneous Poisson process, cluster process, Hawkes process, and spatio-temporal Hawkes process,

2. discussing the algorithms and simulating all of the above processes,

3. extending (temporal) Hawkes process to spatio-temporal Hawkes process, and

4. discussing recent and future work of Hawkes process.




# 2 Definitions and Properties

## 2.1 Counting Process




**Definition 2.1.1** (Stochastic Process) A stochastic process is a family of random variables indexed by time $t$ and is defined as

$$
\{ X(t), t \in T \}
$$




**Definition 2.1.2** (Counting Process) Let *N(t)* be the total number of events up to some time *t* such that the values are nonnegative, interger and nondecreasing, a stocastic process is said to be a counting process and is defined as 

$$
\{N(t), t \geq 0\}
$$




**Definition 2.1.3** (Point Process) Let \{$T_i, i \in N$\} be a sequence of non-negative random variables such that $T_i < T_{i+1}$ $\forall i \in N$, a point process on $R^{+}$ is defined as

$$
\{T_i, i \in N\}
$$




**Definition 2.1.4** (Counting Process) Let \{$T_i, i \in N$\} be a point process, a counting process associated with \{$T_i, i \in N$\} is defined as

$$
N(t) = \sum_{i \in N} I_{\{T_i \leq t\}}
$$




*Corollary* **2.1.1** A counting process satisfies that

1. $N(t) \geq 0$

2. $N(t)$ is an integer

3. If $s \leq t$, then $N(s) \leq N(t)$

4. If $s < t$, then $N(t) - N(s)$ is the number of events occur in the interval (s, t]




**Proposition 2.1.1** A counting process has the following properties

1. (Independence) If the numbers of events $N(t)$ occur in disjoint interval $t$ are independent, a counting process is said to have independent increments.

2. (Stationarity) If the distribution of the numbers of events $N(t)$ depends only on the length of the interval $t$, a counting process is said to have stationary increments.

3. (Homogeneity)

Stationarity implies homogeneity. 




## 2.2 Poisson Process




**Definition 2.2.1** (Poisson Process) If the following conditions hold, a counting process $\{N(t), t \geq 0\}$ is said to be a Poisson Process with constant rate (or intensity) $\lambda > 0$ 

1. $N(0) = 0$

2. $N(t)$ has independent increments

3. $P(N(t + h)) - N(t) = 1)) = \lambda h + o(h)$

4. $P(N(t + h)) - N(t) \geq 2)) = o(h)$

In other words, 1. the process starts at $t = 0$, 2. the increments are independent, 3. $\lambda$ is the rate (or intensity), and 4. no 2 or more events can occur at the same location.




**Proposition 2.2.1** Poisson process has the following properties

1. The number of events in any interval $t$, $N(t)$, $\sim Pos(\lambda t)$. That is, for all $s, t \geq 0$

$$
P(N(t + s) - N(s) = n) = \frac{(\lambda t)^n e^{-\lambda t}} {n!} \ \ 
$$

$n = 0, 1,...$. 


2. The interarrival times, $W$, $\overset{iid}{\sim} exp(\frac{1} {\lambda})$. That is, for rate $\lambda > 0$, the interarrival time $W_i$ $i=1,2,...$ 

$$
P(W_1 > t) = P(N(t) = 0) = e^{-\lambda t}
$$

This is because p($1^{st}$ arrivial arrives after time $t$) is the same as p(no arrivial in the interval [0,$t$]). Similarly, $W_2$ also $\sim exp(\frac{1} {\lambda})$ since

$$
P(W_2 > t | W_1 = s) = P(N(t + s) - N(s)) = P(N(t) = 0) = e^{-\lambda t}. 
$$




## 2.3 Nonhomogeneous Poisson Process




**Definition 2.3.1** (Nonhomogeneous Poisson Process) If the following conditions hold, a counting process $\{N(t), t \geq 0\}$ is said to be a nonhomogeneous Poisson Process with intensity function of time $\lambda(t), t > 0$

1. $N(0) = 0$

2. $N(t)$ has independent increments

3. $P(N(t + h)) - N(t) = 1)) = \lambda(t) h + o(h)$

4. $P(N(t + h)) - N(t) \geq 2)) = o(h)$




**Proposition 2.2.1** Nonhomogeneous Poisson process has the following properties

1. The number of events in any interval $t$, $N(t)$, $\sim Pos(\int_{0}^{t} \lambda (s) ds)$. That is, for all $s, t \geq 0$

$$
P(N(t)= n) = \frac{(\int_{0}^{t} \lambda (s) ds)^n e^{\int_{0}^{t} \lambda (s) ds}} {n!} \ \ 
$$

or 

$$
P(N(b) - N(a) = n) = \frac{(\int_{a}^{b} \lambda (s) ds)^n e^{\int_{a}^{b} \lambda (s) ds}} {n!} \ \ 
$$

$n = 0, 1,...$ 




## 2.4 Cox and Cluster Process

(Cox Process) Let **X** be a Poisson process with intensity function $\Lambda (t)$, then **X** is a Cox process with intensity function $\lambda (t) = E(\Lambda (t))$.

(Cluster Process) 

**Proposition 2.4.1** Cluster Process has the following model assumptions

1. Poisson parents

2. Independent clusters

3. Identically distributed clusters

4. Poisson number of offsprings 

5. Offsprings independent within a cluster 

6. Isotropic clusters

In other words, 1. 'parent' points follow a Poisson distribution, 2. clusters are independent of each other, 3. clusters, when shifted, have the same distributions, 4. the numbers of 'offspring' points of each parent point follow a Poisson distribution, 5. the locations of 'offspring' points of each parent point are independently and identically distributed, and 6. the distribution of 'offspring' points for each parent point depends only on the distance between the 'parent' and the 'offspring'. 

Under assumption 1 - 5, cluster process is a Cox process. 


## 2.5 Hawkes Process 




**Definition 2.5.1** (Hawkes Process) A counting process $\{N(t), t \geq 0\}$ associated with past events $\{\mathcal{H}_{t}^{N}, t > 0\}$ is said to be a Hawkes process with conditional intensity function $\lambda(t | \mathcal{H}_{t}^{N}), t > 0$ and takes the form 

$$
\lambda(t | \mathcal{H}_{t}^{N}) = \lambda_0(t) + \sum^{}_{i: T_i < t} \phi( t - T_i)
$$

where

- $\lambda_0(t)$ is the base intensity function (or $\mu$ the constant background rate)

- $T_i < t$ are the events time occur before current time $t$ 

- $\phi(\cdot)$ is the kernel function (or $g(\cdot)$ the triggering function) through which intensity function depends on past events 

- $\mathcal{H}_{t}^{N}$ is the natural filration (or simply $\mathcal{H}_{t}^{}$ the past history) which represents the internal history of N up to time $t$




*Corollary* **2.5.1** Hawkes process satisfies that

1. $N(t) = 0$

2. $\lambda(t | \mathcal{H}_{t}^{N}) = \lambda_0(t) + \int_{-\infty}^{t} \phi( t - T_i)dN(s) = \lambda_0(t) + \sum^{}_{i: T_i < t} \phi( t - T_i)$

3. $P(N(t + h)) - N(t) = 1) | \mathcal{H}_{t}^{N}) = \lambda(t) h + o(h)$

4. $P(N(t + h)) - N(t) \geq 2) | \mathcal{H}_{t}^{N}) = o(h)$




**2.5.1** Choices of $\phi(\cdot)$ include, for example, exponentially decaying function and power-law kernel, and they take the form of 

$$
\phi(x) = \alpha e^ {-\beta x} 
$$

$$
\phi(x) = \frac{\alpha} { (x + \beta) ^ {\eta + 1}}
$$




**2.5.2** There are two ways to view Hawkes processes

1. Intensity-based Hawkes Process

2. Cluster-based Hawkes Process




## 2.5 Spatio-Temporal Hawkes Process 

Spatio-temporal Hawkes processes is an extention of temporal Hawkes processes. Recall that temporal Hawkes processes take the form of 

$$
\lambda(t | \mathcal{H}_{t}) = \mu + \sum^{}_{i: T_i < t} g(t - t_i)
$$

Spatio-temporal Hawkes processes take the form of 

$$
\lambda(t | \mathcal{H}_{t}) = \mu(s) + \sum^{}_{i: T_i < t} g(s - s_i, t - t_i)
$$

where 

- ${s_i, i = 1,2,...}$ are the sequence of locations of events  

- ${t_i, i = 1,2,...}$ are the times of the events 




Next, we 




# 3 Algorithms and Simulations

## 3.1 Counting Process

## 3.2 Poisson Process

## 3.3 Nonhomogeneous Poisson Process

There are multiple ways to simulate nonhomogeneous Poisson process: 1) inversion, 2) order statistics, 3) thinning and 4) hybride (inversion $+$ thinning). 

In this example, we use the thinning algorithm to simulate nonhomogeneous Poisson process with the intensity function $\lambda (t)=$ ... since it is one of the most popular choices for both temporal and spatio-temporal cases. 

Thinning algorithm involves deleting points from a point pattern. 

## 3.4 Cox and Cluster Process 

## 3.5 Hawkes Process 




# 4 Conclusions and Discussion




\newpage

# Acknowledgments




\newpage

# Reference

Chen, Y. (2016). Thinning algorithms for simulating point processes. Florida State University, Tallahassee, FL.



Obral, K. (2016). Simulation, estimation and applications of hawkes processes. (Master's thesis, University of Minnesota, Twin Cities, United States). 

Rizoiu, M. A., Lee, Y., Mishra, S., & Xie, L. (2017). A tutorial on hawkes processes for events in social media. arXiv preprint arXiv:1708.06401. 

Krishna, R. (2015). Simulation of Non-Homogeneous Poisson Processes. 

Pasupathy, R. (2010). Generating homogeneous poisson processes. Wiley encyclopedia of operations research and management science. 

# Terminology

[Counting Processes](https://www.probabilitycourse.com/chapter11/11_1_1_counting_processes.php)

[Poisson Process](https://www.probabilitycourse.com/chapter11/11_1_2_basic_concepts_of_the_poisson_process.php)

[Nonhomogeneous Poisson Processes](https://www.probabilitycourse.com/chapter11/11_1_4_nonhomogeneous_poisson_processes.php)