---
title: "01_proc_HPP"
author: "Frances Lin"
date: "4/15/2021"
output: pdf_document
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(patchwork)
```

```{r}
set.seed(1) # for reproducibility

lmbda <- 10
t_max <- 10 

t <- 0 
X <- numeric(0) # vector of t

while(t <= t_max){
  u       <- runif(1)
  t       <-  t - log(u)/lmbda                # t ~ exp(1/lambda)
  if(t < t_max) {
    X <- c(X,t)                               # update index 
  }
}
```

```{r}
# Check to see if the total #s matches 
length(X)
```

```{r}
# Create dataframe
df_HPP = tibble(
  x = X, 
  y = 1:(length(X)) #0:(length(X) - 1) 
)

# Plot HPP 
p_HPP <- ggplot(data=df_HPP, mapping=aes(x=x, y=y)) +
  geom_step() + 
  labs(title = "Homogeneous Poisson Process (lambda = 10)", 
       x = "t", 
       y = "N(t)") + 
  xlim(0, 10) # so that scale lines up
#p_HPP
```

```{r}
# # Can probably delete 
# df_HPP <- df_HPP %>% add_column(
#   t_fix = rep(2, length(df_HPP$x))
# ) 

# Plot time plot
p_HPP_time <- ggplot(data=df_HPP, mapping=aes(x=x, ymin = -0.5, ymax = 0.5)) +
  geom_linerange() + 
  geom_hline(aes(yintercept = 0), linetype = "dashed") + 
  labs(title = "Corresponding Inter-Arrivial Times", 
       x = "t", 
       y = "") + 
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, by = 1)) + 
  theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
#p_HPP_time
```

```{r}
# Plot lambda (rate)
p_HPP_hist <- ggplot(data=df_HPP, mapping=aes(x=x)) + 
  geom_histogram(bins = 11, color = "white") + 
  labs(title = "Rate/Intensity",
       x = "t", 
       y = "lambda") + 
  xlim(0, 10) # so that scale lines up
#p_HPP_hist 
```

```{r}
# Combine plots
# require(gridExtra)
# grid.arrange(p_HPP, p_HPP_time)
p_HPP / p_HPP_time / p_HPP_hist + plot_layout(heights = c(0.6, 0.2, 0.2))
```

```{r}
# Save output and adjust size
png(file = '/Users/franceslinyc/Hawkes-Process-2021/results/plot_1D_HPP.png', width = 450*2, height = 450*0.8)
p_HPP / p_HPP_time / p_HPP_hist + plot_layout(heights = c(0.7, 0.1, 0.2))
```



