---
title: "04_proc_using_spatstat"
author: "Frances Lin"
date: "4/8/2021"
output: pdf_document
---

```{r warning=FALSE, message=FALSE}
library(spatstat)
library(tidyverse)
library(here)
library(mvtnorm)
library(ggplot2)
library(patchwork)
```

```{r}
# Cox?
#rmvnorm(1, c(0.5, 0.5))
```

```{r}
# Cox?
#plot(rpoispp(lambda = function(x, y) 400*x*y, win = square(1)), main = "") #plot_2D_NPP
```

```{r}
# Cox?
#fun <- function (x, y) x*y + rbeta(1, 1/5, 1/5)*400
plot(rpoispp(lambda = rbeta(1, 1/5, 1/5)*150, win = square(1)), main = "")
```

```{r}
# Cox?
plot(rpoispp(lambda = rnorm(n = 1, 50, 0.05)), main = "") #plot_2D_Cox
```

```{r}
set.seed(1234) 
par(mfrow=c(1, 4), mai = c(0.1, 0.1, 0.1, 0.1))

plot(rpoispp(lambda = 100, win=square(1)), main = "HPP (rate = 100)") #plot_2D_HPP
plot(rpoispp(lambda = function(x, y) 400*x*y, win = square(1)), main = "NPP (intensity = 400*x*y)") #plot_2D_NPP
plot(rpoispp(lambda = rexp(n = 1, rate = 1/100)), main = "Cox Process") #plot_2D_Cox
plot(rMatClust(kappa = 20, r = 0.05, mu = 5), main = "Matern Process") #plot_2D_Matern

#HPP (rate = 100)
#NPP (intensity = 400*x*y)
#Cox Process
#Matern Process
#Cox (intensity = exp(n = 1, rate = 1/100))
#Matern (kappa = 20, r = 0.05, mu = 5)
```

```{r}
# Cuz I like ggplot better
set.seed(1234) 

# Extract x & y from ppp object (lists)
tmp1 <- rpoispp(lambda = 100, win=square(1))
tmp2 <- rpoispp(lambda = function(x, y) 400*x*y)
tmp3 <- rpoispp(lambda = rexp(n = 1, rate = 1/100))
tmp4 <- rMatClust(kappa = 20, r = 0.05, mu = 5)

# Create dataframes
df1 <- tibble(x = tmp1$x, y = tmp1$y)
df2 <- tibble(x = tmp2$x, y = tmp2$y)
df3 <- tibble(x = tmp3$x, y = tmp3$y)
df4 <- tibble(x = tmp4$x, y = tmp4$y)

n <- 0.5 # set size for geom_point

p1 <- ggplot(df1, aes(x=x, y=y)) + geom_point(size=n) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        axis.title=element_blank()) +
  labs(title="HPP (rate = 100)")

p2 <- ggplot(df2, aes(x=x, y=y)) + geom_point(size=n) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        axis.title=element_blank()) +
  labs(title="NPP")

p3 <- ggplot(df3, aes(x=x, y=y)) + geom_point(size=n) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        axis.title=element_blank()) +
  labs(title="Cox Process")

p4 <- ggplot(df4, aes(x=x, y=y)) + geom_point(size=n) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
        axis.text.y=element_blank(), axis.ticks.y=element_blank(),
        axis.title=element_blank()) +
  labs(title="Matern Process")
```

```{r}
# Combine plots
p1 + p2 + p3 + p4 + plot_layout(ncol = 4) + coord_fixed(ratio = 1)
```


```{r}
# Check to see how to use the function 
?rpoispp
# Check to see how this is written
#View(rpoispp)
```

```{r}
# Plot a homogeneous Poisson process
# p.1334 of https://mran.microsoft.com/snapshot/2016-04-25/web/packages/spatstat/spatstat.pdf
# https://spatstat.org/SSAI2017/solutions/solution04.html

par(mfrow=c(1, 1))
plot_2D_HPP <- plot(rpoispp(lambda = 100, win=square(1)), main = "HPP (rate = 100)")
plot_2D_HPP
#plot(rpoispp(lambda = 50, win=square(1)),main = "HPP (rate = 50)")
#plot(rpoispp(lambda = 10, win=square(1)),main = "HPP (rate = 10)")
```

```{r}
# Plot a nonhomogeneous Poisson process
# p.33 of https://spatstat.org/resources/spatstatJSSpaper.pdf

#lmbda_function <- function(x, y) 400*x 
#so that they have the same expected # of events but why ???

par(mfrow=c(1, 1))
plot_2D_NPP <- plot(rpoispp(lambda = function(x, y) 400*x*y, win=square(1)), main = "NPP (intensity = 400*x*y)")
plot_2D_NPP
#plot(rpoispp(lambda = function(x, y) 50*x, win=square(1)), main = "NPP (intensity = 50*x)")
#plot(rpoispp(lambda = function(x, y) 10*x, win=square(1)), main = "NPP (intensity = 10*x)")
```

```{r}
# Plot a Cox process
# p.80 of https://darrylmcleod.com/wp-content/uploads/2016/06/Analysing-spatial-point-patterns-in-R.pdf

lmbda <- rexp(n = 1, rate = 1/100)
X <- rpoispp(lmbda)
plot(X, main = "Cox (intensity = exp(n = 1, rate = 1/100))")
```


```{r}
?rMatClust
#kappa = intensity
#scale = radius of the clusters
#mu = mean # of points per cluster
```

```{r}
plot_2D_Matern <- plot(rMatClust(kappa = 20, r = 0.05, mu = 5), main = "Matern (kappa = 20, r = 0.05, mu = 5)")
plot_2D_Matern
```

```{r}
?rMaternII
# kappa = intensity
# r = inhibition distance
```

```{r}
# Plot a Matern I process #Inhibition 
par(mfrow=c(1, 1))
plot(rMaternI(kappa = 100, r = 0.1), main = "Matern I (kappa = 100, r = 0.05)")
#plot(rMaternI(kappa = 50, r = 0.05), main = "Matern I (kappa = 50, r = 0.05)")
#plot(rMaternI(kappa = 10, r = 0.05), main = "Matern I (kappa = 10, r = 0.05)")
points <- rMaternI(kappa = 100, r = 0.07)
length(points)
pairdist(points)
min(pairdist(points)[upper.tri(pairdist(points))])
```

```{r}
# Plot a Matern II process
par(mfrow=c(1, 1))
plot(rMaternII(kappa = 100, r = 0.05), main = "Matern II (kappa = 100, r = 0.05)")
#plot(rMaternII(kappa = 50, r = 0.05), main = "Matern II (kappa = 50, r = 0.05)")
#plot(rMaternII(kappa = 10, r = 0.05), main = "Matern II (kappa = 10, r = 0.05)")
```

```{r}
# # Save out results
# write_rds(plot_2D_HPP, here("results", "plot_2D_HPP.jpeg"))
```

```{r}
# # Error checking
# plot_2D_HPP <- readRDS(here("results", "plot_2D_HPP.jpeg"))
# plot_2D_HPP
```



