---
title: "proc_using_spatstat"
author: "Frances Lin"
date: "4/8/2021"
output: pdf_document
---

```{r warning=FALSE, message=FALSE}
library(spatstat)
library(tidyverse)
library(here)
```

```{r}
# Check to see how to use the function 
?rpoispp
# Check to see how this is written
#View(rpoispp)
```

```{r}
# Plot a homogeneous Poisson process
# p.1334 of https://mran.microsoft.com/snapshot/2016-04-25/web/packages/spatstat/spatstat.pdf
# https://spatstat.org/SSAI2017/solutions/solution04.html

par(mfrow=c(1, 1))
plot_2D_HPP <- plot(rpoispp(lambda = 100, win=square(1)),main = "HPP (rate = 100)")
plot_2D_HPP
#plot(rpoispp(lambda = 50, win=square(1)),main = "HPP (rate = 50)")
#plot(rpoispp(lambda = 10, win=square(1)),main = "HPP (rate = 10)")
```

```{r}
# Plot a homogeneous Poisson process
# p.33 of https://spatstat.org/resources/spatstatJSSpaper.pdf

#lmbda_function <- function(x, y) 400*x 
#so that they have the same expected # of events but why ???

par(mfrow=c(1, 1))
plot_2D_NPP <- plot(rpoispp(lambda = function(x, y) 400*x*y, win=square(1)), main = "NPP (intensity = 400*x*y)")
plot_2D_NPP
#plot(rpoispp(lambda = function(x, y) 50*x, win=square(1)), main = "NPP (intensity = 50*x)")
#plot(rpoispp(lambda = function(x, y) 10*x, win=square(1)), main = "NPP (intensity = 10*x)")
```

```{r}
?rMatClust
#kappa = intensity
#scale = radius of the clusters
#mu = mean # of points per cluster or reference intensity ???
```

```{r}
plot_2D_Matern <- plot(rMatClust(kappa = 20, r = 0.05, mu = 5), main = "Matern (kappa = 20, r = 0.05, mu = 5)")
plot_2D_Matern
```

```{r}
?rMaternII
# kappa = intensity
# r = inhibition distance
```

```{r}
# Plot a Matern I process
par(mfrow=c(1, 1))
plot(rMaternI(kappa = 100, r = 0.05), main = "Matern I (kappa = 100, r = 0.05)")
#plot(rMaternI(kappa = 50, r = 0.05), main = "Matern I (kappa = 50, r = 0.05)")
#plot(rMaternI(kappa = 10, r = 0.05), main = "Matern I (kappa = 10, r = 0.05)")
```

```{r}
# Plot a Matern II process
par(mfrow=c(1, 1))
plot(rMaternII(kappa = 100, r = 0.05), main = "Matern II (kappa = 100, r = 0.05)")
#plot(rMaternII(kappa = 50, r = 0.05), main = "Matern II (kappa = 50, r = 0.05)")
#plot(rMaternII(kappa = 10, r = 0.05), main = "Matern II (kappa = 10, r = 0.05)")
```

```{r}
# # Save out results
# write_rds(plot_2D_HPP, here("results", "plot_2D_HPP.jpeg"))
```

```{r}
# # Error checking
# plot_2D_HPP <- readRDS(here("results", "plot_2D_HPP.jpeg"))
# plot_2D_HPP
```



